ci: fix and revamp how we publish documentation with mike
Based on: https://github.com/roedoejet/g2p/pull/342

 - fix publishing the docs on release: using the artifact does not work since
   mike rebuilds on each call to "mike deploy"
 - adopt the same versioning model as g2p: dev is the current main, 0.1.0 and
   other tags for published versions, stable is an alias to the most recently
   published tag, latest is an alias to the most recent thing, be that a
   version or the current main.

Just before merging this PR, we need to manually do

```
mike delete --all
mike deploy -u dev latest
git push origin gh-pages
```

to restart the docs with this changed model. Otherwise, docs.yaml will fail
with this error:
> error: alias 'latest' already specified as a version