build: reconfigure pre-commit in a more standard way
This squashes two commits:

* build: reconfigure pre-commit in a more standard way
* build: reconfigure pre-commit mypy too, and fix a mypy warning

More details from the first of those two commits, showing errors that I
fixed in the second one and the subsequent submodule updates:

Fetch isort and black from their respective pre-commit repos with exact versions.

mypy remains from local install because making the switch to the following
config (which I thought should be correct) causes 5 warnings to appear that
weren't there before.

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        additional_dependencies: [pydantic, numpy<2, types-requests, types-pyyaml, types-setuptools, types-tabulate, types-tqdm]

These are the warnings I'm seeing:

everyvoice/base_cli/callback.py:15: error: Method "on_save_checkpoint" is marked as an override, but no base method was found with this name  [misc]
everyvoice/model/vocoder/HiFiGAN_iSTFT_lightning/hfgl/config/__init__.py:189: error: The erased type of self "builtins.dict[Any, Any]" is not a supertype of its class "type[everyvoice.model.vocoder.HiFiGAN_iSTFT_lightning.hfgl.config.HiFiGANConfig]"  [misc]
everyvoice/model/feature_prediction/FastSpeech2_lightning/fs2/config/__init__.py:278: error: The erased type of self "builtins.dict[Any, Any]" is not a supertype of its class "type[everyvoice.model.feature_prediction.FastSpeech2_lightning.fs2.config.FastSpeech2Config]"  [misc]
everyvoice/model/feature_prediction/FastSpeech2_lightning/fs2/prediction_writing_callback.py:333: error: No overload variant of "decode_tokens" of "TextProcessor" matches argument types "list[int]", "None"  [call-overload]
everyvoice/model/feature_prediction/FastSpeech2_lightning/fs2/prediction_writing_callback.py:333: note: Possible overload variants:
everyvoice/model/feature_prediction/FastSpeech2_lightning/fs2/prediction_writing_callback.py:333: note:     def decode_tokens(self, sequence: list[int], join_character: None, joiner_substitution: None) -> list[str]
everyvoice/model/feature_prediction/FastSpeech2_lightning/fs2/prediction_writing_callback.py:333: note:     def decode_tokens(self, sequence: list[int], join_character: str, joiner_substitution: str) -> str
everyvoice/model/feature_prediction/FastSpeech2_lightning/fs2/prediction_writing_callback.py:333: note:     def decode_tokens(self, sequence: list[int]) -> str
everyvoice/model/e2e/model.py:176: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
everyvoice/model/feature_prediction/FastSpeech2_lightning/fs2/cli/train.py:29: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
everyvoice/model/feature_prediction/FastSpeech2_lightning/fs2/cli/check_data.py:175: error: Incompatible types in assignment (expression has type "None", variable has type "list[dict[Any, Any]]")  [assignment]
Found 5 errors in 5 files (checked 80 source files)